# Generated by Django 4.2.5 on 2023-10-11 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipelines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chosen_work_mode",
                    models.CharField(auto_created="Standart", default="Standart"),
                ),
                ("p_id", models.BigIntegerField()),
                ("text", models.CharField(blank=True, max_length=250000, null=True)),
                ("model", models.CharField(max_length=100, null=True)),
                ("ftmodel", models.CharField(max_length=100, null=True)),
                ("tokens", models.IntegerField(null=True)),
                ("temperature", models.FloatField(null=True)),
                ("voice", models.BooleanField(null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("order_number", models.IntegerField(null=True)),
                ("filename", models.CharField(null=True)),
                ("work_rule", models.JSONField(null=True)),
                ("is_exists", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Statuses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_id", models.IntegerField()),
                ("name", models.CharField(max_length=300)),
                ("order_number", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_exists", models.BooleanField(default=True)),
                (
                    "pipeline_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.pipelines"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GptApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AmoConnect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField()),
                ("host", models.CharField()),
                ("password", models.CharField()),
                ("account_chat_id", models.CharField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
