# Generated by Django 4.2.5 on 2023-10-26 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeMode",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("database_link", models.CharField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="ModeMessages",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("hi_message", models.CharField(default="")),
                ("openai_error_message", models.CharField(default="")),
                ("database_error_message", models.CharField(default="")),
                ("service_settings_error_message", models.CharField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="ModeQualification",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("value", models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name="Pipelines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_id", models.BigIntegerField()),
                ("voice_message_detection", models.BooleanField(null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("order_number", models.IntegerField(null=True)),
                ("chosen_work_mode", models.CharField(default="Prompt mode")),
            ],
        ),
        migrations.CreateModel(
            name="Statuses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_id", models.IntegerField()),
                ("name", models.CharField(max_length=300)),
                ("order_number", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_exists", models.BooleanField(default=True)),
                (
                    "pipeline_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.pipelines"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchMode",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("database_link", models.CharField(default="")),
                ("search_rules", models.JSONField(default=[])),
                ("view_rule", models.CharField(default="")),
                ("results_count", models.IntegerField(default=1)),
                (
                    "mode_messages",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.modemessages",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.modequalification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchAndKnowledgeMode",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "knowledge_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.knowledgemode",
                    ),
                ),
                (
                    "search_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.searchmode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptMode",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("context", models.CharField(default="", max_length=250000)),
                ("model", models.CharField(default="gpt-3.5-turbo", max_length=100)),
                ("max_tokens", models.IntegerField(default=0)),
                ("temperature", models.FloatField(default=1)),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.modequalification",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pipelines",
            name="knowledge_and_search_mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.searchandknowledgemode",
            ),
        ),
        migrations.AddField(
            model_name="pipelines",
            name="knowledge_mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.knowledgemode"
            ),
        ),
        migrations.AddField(
            model_name="pipelines",
            name="prompt_mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.promptmode"
            ),
        ),
        migrations.AddField(
            model_name="pipelines",
            name="search_mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.searchmode"
            ),
        ),
        migrations.AddField(
            model_name="pipelines",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="knowledgemode",
            name="mode_messages",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.modemessages"
            ),
        ),
        migrations.AddField(
            model_name="knowledgemode",
            name="qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.modequalification"
            ),
        ),
        migrations.CreateModel(
            name="GptApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AmoConnect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField()),
                ("host", models.CharField()),
                ("password", models.CharField()),
                ("account_chat_id", models.CharField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
