# Generated by Django 4.2.5 on 2023-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelines",
            name="file_link",
            field=models.CharField(null=True),
        ),
    ]
