# Generated by Django 4.2.5 on 2023-10-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_pipelines_file_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelines",
            name="db_error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pipelines",
            name="hi_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pipelines",
            name="openai_error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pipelines",
            name="success_message",
            field=models.TextField(null=True),
        ),
    ]
