# Generated by Django 4.2.5 on 2023-10-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_pipelines_statuses_gptapikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelines",
            name="filename",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="pipelines",
            name="work_rule",
            field=models.JSONField(null=True),
        ),
    ]
