# Generated by Django 4.2.5 on 2023-10-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_knowledgemode_id_alter_modemessages_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelines",
            name="voice_message_detection",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
