# Generated by Django 4.2.5 on 2023-10-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_pipelines_filename_alter_pipelines_work_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelines",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="statuses",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
