# Generated by Django 4.2.5 on 2023-10-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_pipelines_db_error_message_pipelines_hi_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelines",
            name="view_rule",
            field=models.CharField(null=True),
        ),
    ]
