# Generated by Django 4.2.5 on 2023-11-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_knowledgemode_database_file_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modequalification",
            name="qualification_finished",
            field=models.CharField(default=""),
        ),
    ]
