# Generated by Django 4.2.5 on 2023-10-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_statuses_status_id_alter_statuses_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuses",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
