# Generated by Django 4.2.5 on 2023-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_pipelines_results_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualificationMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_id", models.BigIntegerField()),
                ("qualification_rules", models.JSONField(null=True)),
                ("qualification_repeat_time", models.IntegerField(null=True)),
                ("qualification_repeat_count", models.IntegerField(null=True)),
                ("gpt_not_qualified_message_time", models.IntegerField(null=True)),
                ("gpt_not_qualified_question_time", models.IntegerField(null=True)),
                ("file_link", models.CharField(null=True)),
                ("hi_message", models.CharField(null=True)),
                ("openai_error_message", models.CharField(null=True)),
                ("db_error_message", models.CharField(null=True)),
            ],
        ),
    ]
