# Generated by Django 4.2.5 on 2023-10-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_statuses_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelines",
            name="is_exists",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="statuses",
            name="is_exists",
            field=models.BooleanField(default=True),
        ),
    ]
