# Generated by Django 4.2.5 on 2023-11-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_modequalification_qualification_finished"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField()),
                ("period", models.IntegerField()),
                ("owner_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_type", models.IntegerField()),
                ("date", models.DateField()),
                ("amount", models.FloatField()),
                ("payment_id", models.TextField()),
                ("owner_id", models.IntegerField()),
                ("is_finished", models.BooleanField()),
            ],
        ),
    ]
