# Generated by Django 4.2.5 on 2023-10-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_qualificationmode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualificationmode",
            name="gpt_not_qualified_message_time",
            field=models.IntegerField(auto_created=60, default=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="qualificationmode",
            name="gpt_not_qualified_question_time",
            field=models.IntegerField(auto_created=60),
        ),
        migrations.AlterField(
            model_name="qualificationmode",
            name="qualification_repeat_count",
            field=models.IntegerField(auto_created=2),
        ),
        migrations.AlterField(
            model_name="qualificationmode",
            name="qualification_repeat_time",
            field=models.IntegerField(auto_created=30),
        ),
    ]
