# Generated by Django 4.2.5 on 2023-10-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_pipelines_is_exists_statuses_is_exists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelines",
            name="chosen_work_mode",
            field=models.CharField(auto_created="Standart", default="Standart"),
        ),
    ]
