# Generated by Django 4.2.5 on 2023-11-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_subscriptions_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptions",
            name="transaction_id",
            field=models.IntegerField(default=None),
        ),
    ]
