# Generated by Django 4.2.5 on 2023-10-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "home",
            "0008_alter_qualificationmode_gpt_not_qualified_message_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualificationmode",
            name="gpt_not_qualified_message_time",
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="qualificationmode",
            name="gpt_not_qualified_question_time",
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="qualificationmode",
            name="qualification_repeat_count",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="qualificationmode",
            name="qualification_repeat_time",
            field=models.IntegerField(default=30),
        ),
    ]
