# Generated by Django 4.2.5 on 2023-11-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_subscriptions_transaction_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarexSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knowledge_link", models.CharField(max_length=100)),
                ("context", models.CharField(max_length=30000)),
                ("api_token", models.CharField(max_length=100)),
                ("error_message", models.CharField(max_length=30000)),
            ],
        ),
    ]
