# Generated by Django 4.2.5 on 2023-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_avatarexsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmoRegisterTry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=1000, null=True)),
                ("password", models.CharField(max_length=1000, null=True)),
                ("host", models.CharField(max_length=1000, null=True)),
                ("amo_hash", models.CharField(max_length=1000, null=True)),
                ("api_auth_passed", models.BooleanField(null=True)),
                ("site_auth_passed", models.BooleanField(null=True)),
            ],
        ),
    ]
