# Generated by Django 4.2.5 on 2023-11-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_amoregistertry"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgemode",
            name="prompt_mode_id",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="promptmode",
            name="error_message",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="promptmode",
            name="error_message_time",
            field=models.IntegerField(default=3, null=True),
        ),
    ]
