# Generated by Django 4.2.5 on 2023-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_knowledgemode_prompt_mode_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptmode",
            name="connected_to",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="promptmode",
            name="working_stages",
            field=models.JSONField(default=None, null=True),
        ),
    ]
